public enum PlayerBaseAssetEnum
{
    NONE,
    PLAYER_FEMALE_BASE_01,
    PLAYER_ADVENTURER_BASE_01,
    //PLAYER_FEMALE_BASE_02,
    //PLAYER_FEMALE_BASE_03,
    //PLAYER_FEMALE_BASE_04,
    //PLAYER_FEMALE_BASE_05,
}